/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAssetListFactoryHolder,
  IAssetListFactoryHolderInterface,
} from "../IAssetListFactoryHolder";

const _abi = [
  {
    inputs: [],
    name: "assetListFactory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAssetListFactoryHolder__factory {
  static readonly abi = _abi;
  static createInterface(): IAssetListFactoryHolderInterface {
    return new Interface(_abi) as IAssetListFactoryHolderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAssetListFactoryHolder {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAssetListFactoryHolder;
  }
}
