/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAssetListFactory,
  IAssetListFactoryInterface,
} from "../IAssetListFactory";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "asset",
            type: "address",
          },
          {
            internalType: "address",
            name: "priceFeed",
            type: "address",
          },
          {
            internalType: "uint8",
            name: "decimals",
            type: "uint8",
          },
          {
            internalType: "uint64",
            name: "borrowCollateralFactor",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "liquidateCollateralFactor",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "liquidationFactor",
            type: "uint64",
          },
          {
            internalType: "uint128",
            name: "supplyCap",
            type: "uint128",
          },
        ],
        internalType: "struct CometConfiguration.AssetConfig[]",
        name: "assetConfigs",
        type: "tuple[]",
      },
    ],
    name: "createAssetList",
    outputs: [
      {
        internalType: "address",
        name: "assetList",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAssetListFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IAssetListFactoryInterface {
    return new Interface(_abi) as IAssetListFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAssetListFactory {
    return new Contract(address, _abi, runner) as unknown as IAssetListFactory;
  }
}
