/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockFeedDec18__factory } from "./MockFeedDec18__factory";
export { MockFeedDec8__factory } from "./MockFeedDec8__factory";
