/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  Deployable,
  DeployableInterface,
} from "../../CometProxyAdmin.sol/Deployable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
    ],
    name: "deploy",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class Deployable__factory {
  static readonly abi = _abi;
  static createInterface(): DeployableInterface {
    return new Interface(_abi) as DeployableInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Deployable {
    return new Contract(address, _abi, runner) as unknown as Deployable;
  }
}
