/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CometCore {
  export type AssetInfoStruct = {
    offset: BigNumberish;
    asset: AddressLike;
    priceFeed: AddressLike;
    scale: BigNumberish;
    borrowCollateralFactor: BigNumberish;
    liquidateCollateralFactor: BigNumberish;
    liquidationFactor: BigNumberish;
    supplyCap: BigNumberish;
  };

  export type AssetInfoStructOutput = [
    offset: bigint,
    asset: string,
    priceFeed: string,
    scale: bigint,
    borrowCollateralFactor: bigint,
    liquidateCollateralFactor: bigint,
    liquidationFactor: bigint,
    supplyCap: bigint
  ] & {
    offset: bigint;
    asset: string;
    priceFeed: string;
    scale: bigint;
    borrowCollateralFactor: bigint;
    liquidateCollateralFactor: bigint;
    liquidationFactor: bigint;
    supplyCap: bigint;
  };
}

export interface IAssetListInterface extends Interface {
  getFunction(nameOrSignature: "getAssetInfo" | "numAssets"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAssetInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "numAssets", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "getAssetInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "numAssets", data: BytesLike): Result;
}

export interface IAssetList extends BaseContract {
  connect(runner?: ContractRunner | null): IAssetList;
  waitForDeployment(): Promise<this>;

  interface: IAssetListInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAssetInfo: TypedContractMethod<
    [i: BigNumberish],
    [CometCore.AssetInfoStructOutput],
    "view"
  >;

  numAssets: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAssetInfo"
  ): TypedContractMethod<
    [i: BigNumberish],
    [CometCore.AssetInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "numAssets"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
