/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CometConfiguration {
  export type AssetConfigStruct = {
    asset: AddressLike;
    priceFeed: AddressLike;
    decimals: BigNumberish;
    borrowCollateralFactor: BigNumberish;
    liquidateCollateralFactor: BigNumberish;
    liquidationFactor: BigNumberish;
    supplyCap: BigNumberish;
  };

  export type AssetConfigStructOutput = [
    asset: string,
    priceFeed: string,
    decimals: bigint,
    borrowCollateralFactor: bigint,
    liquidateCollateralFactor: bigint,
    liquidationFactor: bigint,
    supplyCap: bigint
  ] & {
    asset: string;
    priceFeed: string;
    decimals: bigint;
    borrowCollateralFactor: bigint;
    liquidateCollateralFactor: bigint;
    liquidationFactor: bigint;
    supplyCap: bigint;
  };
}

export interface IAssetListFactoryInterface extends Interface {
  getFunction(nameOrSignature: "createAssetList"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createAssetList",
    values: [CometConfiguration.AssetConfigStruct[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "createAssetList",
    data: BytesLike
  ): Result;
}

export interface IAssetListFactory extends BaseContract {
  connect(runner?: ContractRunner | null): IAssetListFactory;
  waitForDeployment(): Promise<this>;

  interface: IAssetListFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createAssetList: TypedContractMethod<
    [assetConfigs: CometConfiguration.AssetConfigStruct[]],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createAssetList"
  ): TypedContractMethod<
    [assetConfigs: CometConfiguration.AssetConfigStruct[]],
    [string],
    "nonpayable"
  >;

  filters: {};
}
