/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockFeedDec18 } from "./MockFeedDec18";
export type { MockFeedDec8 } from "./MockFeedDec8";
export * as factories from "./factories";
export { MockFeedDec18__factory } from "./factories/MockFeedDec18__factory";
export { MockFeedDec8__factory } from "./factories/MockFeedDec8__factory";
